# Generated by Django 6.0.4 on 2026-04-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
